before_script:
  - 'apt-get install python-pip python3-pip'
  - 'python -m pip install --upgrade pip'
  - 'python3 -m pip install --upgrade pip'
  - 'pip3 install --upgrade click'

draft:
  image: philipptempel/docker-ubuntu-tug-texlive:2020
  stage: build
  script:
    - 'make draft'
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    paths:
      - '*.pdf'
  tags:
    - docker

final:
  image: philipptempel/docker-ubuntu-tug-texlive:2020
  stage: build
  script:
    - 'make final'
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    paths:
      - '*.pdf'
  tags:
    - docker

