draft:
  image: registry.gitlab.com/philipptempel/docker-ubuntu-tug-texlive/latest:full
  stage: build
  script:
    - 'make draft'
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    paths:
      - '*.pdf'
  tags:
    - docker

final:
  image: registry.gitlab.com/philipptempel/docker-ubuntu-tug-texlive/latest:full
  stage: build
  script:
    - 'make final'
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    paths:
      - '*.pdf'
  tags:
    - docker
  only:
    - master
    - main
